//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hole
    {
        public Hole()
        {
            this.Rounds = new HashSet<Round>();
            this.Scores = new HashSet<Score>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public int Par { get; set; }
        public Nullable<int> TotalYards { get; set; }
        public Nullable<int> YardsFromBlue { get; set; }
        public Nullable<int> YardsFromWhite { get; set; }
        public Nullable<int> YardsFromRed { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> Score { get; set; }
        public string Name { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Round> Rounds { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
    }
}
