//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Round
    {
        public Round()
        {
            this.ScoreCards = new HashSet<ScoreCard>();
            this.Holes = new HashSet<Hole>();
            this.Players = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime RoundDate { get; set; }
        public int CourseId { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<ScoreCard> ScoreCards { get; set; }
        public virtual ICollection<Hole> Holes { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
