//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int id { get; set; }
        public int ScoreCardid { get; set; }
        public Nullable<int> Strokes { get; set; }
        public int Holeid { get; set; }
        public Nullable<int> PuttLength { get; set; }
        public Nullable<int> PuttCount { get; set; }
        public Nullable<int> DrivingDist { get; set; }
        public Nullable<int> AverageDrive { get; set; }
        public Nullable<int> SandSaveCount { get; set; }
        public Nullable<bool> FairwayHit { get; set; }
        public Nullable<int> Par3Average { get; set; }
        public Nullable<int> Par4Average { get; set; }
        public Nullable<int> Par5Average { get; set; }
        public string Comments { get; set; }
    
        public virtual ScoreCard ScoreCard { get; set; }
        public virtual Hole Hole { get; set; }
    }
}
